author: eccentric_nz
description: Debugging setting entity velocity
main: me.eccentric_nz.setentityvelocity.SetEntityVelocity
name: SetEntityVelocity
load: POSTWORLD
version: 1.0.0
api-version: '1.21'
website: http://tardisjenkins.duckdns.org:8080/job/setentityvelocity
dev-url: http://tardisjenkins.duckdns.org:8080/job/setentityvelocity
permissions:
    setentityvelocity.use:
        description: A description.
        default: op
commands:
    setentityvelocity:
        aliases: [sev]
        description: A description.
        usage: /<command> [x] [y] [z]
        permission: setentityvelocity.use
        permission-message: You don't have the permission <permission> to use this command
